This jupyter notebook belongs to 'Bioinformatics Algorithms chapter 3: Sequence alignment using dynamic programming'

Exercise: How many different paths are there from source to sink in a 16 × 12 rectangular grid?<br>
Note: Keep in mind that according to our notation, a 16 × 12 grid contains 17 × 13 = 221 nodes.

(16x12)!/(16!*12!)

RecursiveChange(money,coins)<br>
Sample input:<br>
76<br>
[5,4,1]<br>
Sample output:<br>


In [2]:
def recursive_change(money, coins):
    if money == 0:
        return 0
    min_num_coins = 2000
    for coin in coins:
        if money >= coin:
            num_coins = recursive_change(money - coin, coins)
            if num_coins + 1 < min_num_coins:
                min_num_coins = num_coins + 1
    return min_num_coins
recursive_change(20,[10,5])

2

Exercise: Use dynamic programming to fill in the next ten values of MinNumCoins(m) (i.e., for 13 ≤ m ≤ 22). Place all the values on a single line.

3 3 3 4 4 4 4 4 5 5

Code Challenge: Solve the Change Problem. The DPChange pseudocode is reproduced below for your convenience.<br>
Input: An integer money and an array Coins = (coin1, ..., coind).<br>
Sample input: <br>
40<br>
50,25,20,10,5,1<br>
Output: The minimum number of coins with denominations Coins that changes money.<br>
2

In [3]:
def dp_change(money, coins):
    min_num_coins = {}
    min_num_coins[0] = 0
    for m in range(1,money+1):
        min_num_coins[m] = 2000
        for coin in coins:
            if m >= coin:
                if min_num_coins[m-coin] + 1 < min_num_coins[m]:
                    min_num_coins[m] = min_num_coins[m-coin] + 1
    return min_num_coins[money]

In [4]:
dp_change(16331,[20,19,15,14,11,5,3,1])

817

Find the length of a longest path in the Manhattan Tourist Problem.<br>
Input: Integers n and m, followed by an n × (m + 1) matrix Down and an (n + 1) × m matrix Right. <br>
The two matrices are separated by the "-" symbol.<br>
Sample input<br>
4 4<br>
1 0 2 4 3<br>
4 6 5 2 1<br>
4 4 5 2 1<br>
5 6 8 5 3<br>
-<br>
3 2 4 0<br>
3 2 4 2<br>
0 7 3 3<br>
3 3 0 2<br>
1 3 2 2<br>
Output: The length of a longest path from source (0, 0) to sink (n, m) in the n × m rectangular grid whose edges <br>
are defined by the matrices Down and Right.<br>
Sample output<br>
34

In [5]:
def manhattan_tourist(n,m,downs,rights):
    s = numpy.zeros(shape = (n+1,m+1))
    s[0,0] = 0
    for i in range(1,n+1):
        s[i,0] = s[i-1,0] + downs[i-1,0]
    for j in range(1,m+1):
        s[0,j] = s[0,j-1] + rights[0,j-1]
    for i in range(1,n+1):
        for j in range(1,m+1):
            s[i,j] = max(s[i-1,j] + downs[i-1,j], s[i,j-1] + rights[i,j-1])
    return s[n,m]

In [6]:
import numpy
with open('p245_data.txt') as f:
    nm = f.readline().strip('\n').split(' ')
    n = int(nm[0])
    m = int(nm[1])
    downs = numpy.zeros(shape=(n,m+1))
    rights = numpy.zeros(shape=(n+1,m))
    line = ''
    for i in range(n):
        line = f.readline().strip('\n').split(' ')
        downs[i] = line
    line = f.readline()
    line = ''
    for i in range(n+1):
        line = f.readline().strip('\n').split(' ')
        rights[i] = line
    f.close()    
manhattan_tourist(n,m,downs,rights)

91.0

Backtracking of two strings v and w. Input: two strings v and w. Output: backtracking matrix, shaped len(v)+1 by len(w)+1

In [7]:
def backtrack_lcs(v,w):
    s = numpy.zeros(shape = (len(v)+1,len(w)+1))
    backtrack = numpy.zeros(shape = (len(v)+1,len(w)+1))
    for i in range(1,len(v)+1):
        for j in range(1,len(w)+1):
            if v[i-1] == w[j-1]:
                s[i,j] = max(s[i-1,j], s[i,j-1], s[i-1,j-1]+1)
            else:
                s[i,j] = max(s[i-1,j], s[i,j-1])
            if s[i,j] == s[i-1,j]:
                backtrack[i,j] = '1' #1 equals down
            elif s[i,j] == s[i,j-1]:
                backtrack[i,j] = '2' #2 equals right
            elif s[i,j] == s[i-1,j-1] + 1 and v[i-1] == w[j-1]:
                backtrack[i,j] = '3' #3 equals diagonally
    print('s',s)
    return backtrack
backtrack_lcs('actg','actg')

s [[0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1.]
 [0. 1. 2. 2. 2.]
 [0. 1. 2. 3. 3.]
 [0. 1. 2. 3. 4.]]


array([[0., 0., 0., 0., 0.],
       [0., 3., 2., 2., 2.],
       [0., 1., 3., 2., 2.],
       [0., 1., 1., 3., 2.],
       [0., 1., 1., 1., 3.]])

Use output_lcs to solve the Longest Common Subsequence Problem.<br>
Input: Two strings s and t.<br>
Sample input:<br>
AACCTTGG<br>
ACACTGTGA<br>
Output: A longest common subsequence of s and t. (Note: more than one solution may exist, in which case you may output any one.)<br>
Sample output:<br>
AACTGG

In [8]:
def output_lcs(backtrack, v, i, j):
    if i == 0 or j == 0:
        return
    if backtrack[i,j] == 1:
        output_lcs(backtrack, v, i-1, j)
    elif backtrack[i,j] == 2:
        output_lcs(backtrack, v, i, j-1)
    else:
        output_lcs(backtrack, v, i-1, j-1)
        print(v[i-1], end = '')
s = 'CTTTACTTCAGCGTCCGAGCAGTGATCTTGTTGTCCTTCTTACACTGCAGACAGTGTGTCGCCAGGCCCCCCCTCTATGTATTACTGGCACGGAACTATCTTATCATAAGAACTACGTTAGTGCTTTTTATTCCAACCGGCCCGATTGTGTACCCAATACTTGGGCTACTAAGACCTGTACGATCCCAGTAGCTGCTACACTTCATGCTACACCCTCATCGTCCTGGGACGGCACCCCCTCATGGGCGAGATAGATTAAAGACCGCATCTCTGACCAAAACAGAAATACCTTTGCAGAGGGACTCTTACTTGCTCAGCATTGCCCGCAATCATGCTTCATATTGTCCAAACGCGTCGCCTACCGCGTAATCCGGAAAATGTCTGCATTAGGGTCAACGCGGGACTGACGAGACTCGTACACTCACTACCTACGTGATAAGTCTACTGGCATCTTGCATATACTGCTTCACAAGTTCCCTGGGGCACTAGTTTAAAGGTATTCGTAATAGGAGGACCGCGACAAACAGTCACCTTGGATGGCGGTATACTAGTCAGATAGGCGCGCAACTTACGGCCCTCGGGGCGCTCCACACTGAGCCAAGAAATTTCACGCCTGCGTATTGACAATAACGGAGTGTTTACGAGTCCAGGCTGACTGGAAATGGTTCCGATTTTTATTAGAGTGTCCGATTCCCGAGTGCGCTGGCATTCGCTCCTCTCCTGCAGATAAATTGCCGTCCTTACAAAGAAGGATTGTTATATATCCTCGCGTAGAAACTATTTAGTTCTATTGTGTATAAGCCATCT'
t = 'TATTTAGGAATTGGGATCCTGCTCGTTCTCCCCACTCCATACAAGTGATCTGCGGGAGGGGGTTGATGGATATACCGACTAGCCAAGCTGAAAGAAGTACCATCGTAAGCGCATCTTTAGTCTTAGGGTGTAGGGCAGCAGTTTCGCAACCGGCGAAACGTAAGCTTTTTTGAGTCCCTGTAGATTCCACGTGTCTAGGGGCCTCGACTATCCGAGTGGCTCTTGTCCGTCGGGTATGCAATGTGCCCCGGCGGAAGACGCTTGCTTGCGACACCCGACTGTCCGAACTCCCCCCGGATCGGTCGATAGAACACGACTTAAGCGATACTGTCTCGTGCACACTGGGCTCAGTAGTTACGTTTTCAATCTACAACCCTCGATACTTCCGCGCCGGCCAGAGGAGGGCAGGGCGGGTGATGTATGTCAGCCTACAGTGGCGAATCCCGAACTAAGGTCCGACAGACCCAGTATATGTAACGCTTCAACCTACATCGACGCCCAGATGTGAGGCCCGAGTAGGATCTGGCTCAAAGTAGCTGCATATCTCCATCTGCGTGTTCTATTAAATTAGGTTCGGACCATGCCTTTTTGTGGTCGGCATGCACCTACGTCGACCCGGTCTGCTCTCGATGACCTATTTGAGTTTCTCTCTATACTAATCGCGACCCTGGCAAGTGCAGATAGGAGTCTCTGGCCGATCTGGGAGATCCTGAGACTAAGGGCCACACTTGACATGAGTTAGCTTGGTAAGTATACACAAAATCCTCCAGTTTACTCAGGTCGACACAGGCATTAACAAGTATCTAAATCCAGATAGCACTCGACGCCGGGGGAGTGAAATTTCACCCAGTGACTAACATTACAGCATACGTGGCCCGATTGAGCGACCGCAAACAAATTGGTCCTTAAGCTGAGTACTCTTAGTA'
backtrack = backtrack_lcs(s,t)
output_lcs(backtrack, s, len(s),len(t))

s [[  0.   0.   0. ...   0.   0.   0.]
 [  0.   0.   0. ...   1.   1.   1.]
 [  0.   1.   1. ...   2.   2.   2.]
 ...
 [  0.   1.   2. ... 556. 557. 557.]
 [  0.   1.   2. ... 556. 557. 557.]
 [  0.   1.   2. ... 557. 557. 557.]]
TTTTAGGTGGGATCTTGTTTCCCCACTCAACAGTGTGCGAGGTTATGTATACTGCACGGAATACATCTAAGATCTTAGTCTTATTAGGCCGTTTGACCCAAACGTACTAGCCTGTAGATCCCGTGCTGCTCACTTCATGCTCTTGTCCTGGGACGGCCCCGGCGGAAGATTGCCGCACCGACCCGAATCCCGAGGGATCACGCTAGCATTGCCGCAACTGCTCATATTGTCCAAACCTCGTACCGCGCCGGAAGGAGGGCAGCGGGATGACAGCCTACATCATCCCGATAAGTCACGCATTTGTAACGCTTCACAATCCCTGGGGCCAGTAGGATTCTAAAGAGCGCAACTCACTGGTGCTATATAGTCGATGGCGCGCACTACGGCCCGGCGCTCCATGACCAAGTTTCCTCTATACAATACGGAGTGTAGAGTCCGGCTGACTGGAAAGGCCATTTTTATTGGTGTCCATTCCGAGTCGCGGCATTCGCTCCTCTCCGCAGTAAATTCCGTCCTTACAGAAGGATTGAACCGCAAACATTGTCTAGTGATACCAT

Longest Path in a DAG Problem.<br>
Input: An integer representing the starting node to consider in a graph, followed by an integer <br>
representing the ending node to consider, followed by a list of edges in the graph. <br>
The edge notation "0->1:7" indicates that an edge connects node 0 to node 1 with weight 7. <br>
You may assume a given topological order corresponding to nodes in increasing order.<br>
Sample input:<br>
0<br>
4<br>
0->1:7<br>
0->2:4<br>
2->3:2<br>
1->4:1<br>
3->4:3<br>
Output: The length of a longest path in the graph, followed by a longest path. <br>(If multiple longest paths exist, you may return any one.)<br>
Sample output:<br>
9<br>
0->2->3->4

In [9]:
def longest_path_DAG(start_node, end_node, edges_text):
    
    #order is TO WHICH NODE / FROM WHICH NODE / EDGE VALUE
    incoming_edges = [] #data
    longest_path = [] #output maximizing score
    nodes = [] #node names
    scores = [] #max scores per node filled by memoization/dynamic programming
    backtrack = [] #best node to go back to from current node
    
    for i in range(len(edges_text)):
        edge = edges[i].replace(':','->')
        edge = re.split(r'->',edge)
        edge = [int(e) for e in edge]
        incoming_edges.append(edge)
    incoming_edges = numpy.array(incoming_edges)
    incoming_edges = incoming_edges[incoming_edges[:,0] >= start_node]
    incoming_edges = incoming_edges[incoming_edges[:,1] <= end_node]
    incoming_edges = incoming_edges[incoming_edges[:,0].argsort()]
    nodes = list(numpy.unique(incoming_edges[:,0:2]))
    scores.append(0)
    backtrack.append(0)
    for i in range(1,len(nodes)):
        from_node = nodes[i-1]
        to_node = nodes[i]
        edges_here = incoming_edges[incoming_edges[:,1] == to_node]
        if len(edges_here) == 0: 
            scores.append(-100000)
            backtrack.append('na')
        else:
            s = []
            for edge_here in edges_here:
                try:
                    origin = nodes.index(edge_here[0])
                except:
                    origin = 0
                s.append(scores[origin] + edge_here[2])
            max_score = max(s)
            max_score_index = s.index(max_score)
            scores.append(max(s))
            backtrack.append(edges_here[max_score_index,0])
    print('nodes',nodes,len(nodes))
    print('scores',scores,len(scores))
    print('backtrack',backtrack,len(backtrack))
    path_position = end_node
    while path_position != start_node:
        longest_path.append(path_position)
        path_position = backtrack[nodes.index(path_position)]
    longest_path.append(0)
    longest_path.reverse()
    longest_path = [str(item) for item in longest_path]
    print(scores[-1])
    print('->'.join(longest_path))
        
import re    
import numpy
with open('p253_data.txt') as f:
    start_node = int(f.readline().strip('\n'))
    end_node = int(f.readline().strip('\n'))
    edges = f.readlines()
    edges = [edge.strip('\n') for edge in edges]
f.close()
longest_path_DAG(start_node, end_node, edges)

nodes [0, 1, 2, 3, 4, 5, 6] 7
scores [0, 5, 7, 5, 11, 14, 15] 7
backtrack [0, 0, 1, 0, 2, 1, 5] 7
15
0->1->5->6


Global Alignment Problem.<br>
Input: Two protein strings written in the single-letter amino acid alphabet.<br>
Sample input: <br>
PLEASANTLY<br>
MEANLY<br>
Output: The maximum alignment score of these strings followed by an alignment achieving this maximum score. <br>
Use the BLOSUM62 scoring matrix for matches and mismatches as well as the indel penalty σ = 5.<br>
Sample ouput:<br>
8<br>
PLEASANTLY<br>
-MEA--N-LY

In [10]:
def global_backtrack_lcs(v, w, indel_penalty, matrix):
    s = numpy.zeros(shape = (len(v)+1,len(w)+1))
    global_backtrack = numpy.zeros(shape = (len(v)+1,len(w)+1))
    for i in range(len(v)+1):
        s[i,0] = -i*indel_penalty
    for i in range(len(w)+1):
        s[0,i] = -i*indel_penalty
    for i in range(1,len(v)+1):
        for j in range(1,len(w)+1):
            options = [s[i-1,j] - indel_penalty, s[i,j-1] - indel_penalty, s[i-1,j-1] + matrix[v[i-1]][w[j-1]]]
            s[i,j] = max(options)
            global_backtrack[i,j] = options.index(s[i,j]) + 1    #1 for up, 2 for left, 3 for diagonally
    return global_backtrack

def global_output_lcs(global_backtrack, v, w, v_out, w_out, i, j, score):
    if i == 0 or j == 0:
        if i == 0 and j != 0:
            v_out = v_out + '-'
            w_out = w_out + w[0]
            score = score - indel_penalty
            print(score)
        if i != 0 and j == 0:
            v_out = v_out + v[0]
            w_out = w_out + '-'
            score = score - indel_penalty
            print(score)
        if i == 0 and j == 0:
            print(score)
        print(v_out[::-1])
        print(w_out[::-1])
        return
    if global_backtrack[i,j] == 1:
        v_out = v_out + v[i-1]
        w_out = w_out + '-'
        score = score - indel_penalty
        global_output_lcs(global_backtrack, v, w, v_out, w_out, i-1, j, score)
    elif global_backtrack[i,j] == 2:
        v_out = v_out + '-'
        w_out = w_out + w[j-1]
        score = score - indel_penalty
        global_output_lcs(global_backtrack, v, w, v_out, w_out, i, j-1, score)
    elif global_backtrack[i,j] == 3:
        v_out = v_out + v[i-1]
        w_out = w_out + w[j-1]
        score += matrix[v[i-1]][w[j-1]]
        global_output_lcs(global_backtrack, v, w, v_out, w_out, i-1, j-1, score)
        
import pandas
matrix = pandas.read_csv('blosum62.txt', sep = ' ', index_col = 'names')
indel_penalty = 5
s = 'NQGIHKKLEAMCNPHYARCYFRMWGEIRVFNCMYQWYVLNYLCPTMAHAMFGYLTEPIMEVLRTIQVPYKPIGYICKAGKDEMAWWPHVIQNDIVMWGFKCNKDEPVPPTKTWVCMKELIKDCSWQGVEFVGRTQGPEGSYQGSPTAGQDDGLQKQGRVMTLAWMCEQMDLRATDPRVRGAELEIQKDWEKPDICYMPCCHCWVEALHVGKLVCGYEQQMESPINTEFTYNIAIMMVAWLNRLVDDYVPHMEYMKMEFRGRDPLCEYMGSGVCISYYILMYNSIQYQGYWWCLDSADETAWSMTVLKHNDTTGMPNTMVDKDERRVQCQGIIAGGFWQCFDYSTKMTNLVVKILVWRWWLHTDRSKEPDWVNMVWGFFMAGSVWAYARCCIYAEPVQAMDTMGLQTTPPWMHQDGRIRPGPYRWKEYVWADFKKYPRIPSWGKFHVNRMYRWNNMHHALCWSTKGNPVDTAAQSLYWQFNSDNYNVDTFFPCREMSPMRYIIMYWLTIWIENHCKDMNSFGTVDMPYHPPTPSGGWWCKTQMCHPDKGVIGCRNEHQQRQYGDEKCCCTTFMAFQNNCFHKQRGFWKGFEQATTDMNCTWAINYRGNIKVAQEPCLLEMTGMMGYWRPCTAMNATPYAPHQNQCCQQHAKMKDQEPNFGKTFFWNLYILPTIHQWPLWWRQMRNYTPMNKEMKAQPVTRYAWVWEQKGVFIIWYVLAHKMGFNFPHATGGESHKMCEMINWRAIIPCGAYHNHKTRGCKAMKQDSFEAPGISPGVFDAELMMSFPPEVIGLPNNWSRFVSSMRYKSEMAEMWQKCMWGWTNNSAHDVHQAPYPILGFYAGEGKHSKFMCAMGHAPTWVHVRMVLRSEPINLRNSWNEAGGMPNPLAIDEPPYM'
t = 'NQGIMCNPHYRREAKHPQYWYVLNNMWRGGVRESGYLTEPIMEVLIQVPYKRVRHQCGPGYECKAGKDEMAWWRWDLTVIQNDIVMWGFKCNKDPPVPLVTWVCMKELIKDCSWQGCEDGCMGLGQPVGRTSPCSDWASTYAGQDDGLQKQCRVMTLAWMCEQMDVRATDPRVRGYELIHEVWHPKEVENLWYEQQMIETSPINTEFTEPIWIMMGAWLVDVYVAHMEYMEFRGKDPLCEMMGSEVCISYYILQDTLWMKLCQGYWWQYWPMAVSADETWWSMTVNDKWIIIHNDTTGMPNGMVDKDERRVQCQGIIAGGFWQCFDVLITMNYVATPMTNLVVKILHTPRSKEPDDGVARCDTMGSRVQTTPPWMEQDGRLRPYPYSSTVHIHEWKEYYWADFKKYPRIPEYERGMPEGYRWNNMHHAWCWSTFQPHGNPVDPWFHMPGSGYAQSLYYQFNSRNYNVDTFFPCREMSPMRYIIMYWLTIWINHCKDMNSFGTVDMPYHPPTPSWQMCHPGCRNEHQGRNEPEAATYGSEKCCCTTFMAFQANCFWPRRGFWYFSTGFEQATTNMNCTWAINYRGNIKVAQIPLLEMTGMMGYAIQFEPCTAMNATPYAPHQYQCCQGNAMVIGRFCTLEDQEPNFGKTFFWNLYEKNTHQWPCWHRQMRNKTPMNKEMKRQPVTRYAWEQKGVFIIWYVLAHKMGFNFPHATGGELWCKECHYHKMCEFINERMIEYSSHPCKAMKQDSFEHPGISPGVFDAEFAEQDWTMMSFPPEVIKLPNQLWSAFKSSMPEGWTHISYKSSMGEMWQKLQRMEMWGWTNNSQHDMSTDARYMHQAPCFILGFYAGEYPIEDNGKLSKFMCAMGHAPMWPLNVWVHARMVLRSGEFGGMPNPLAIDEPPYM'
s_out = ''
t_out = ''
score = 0
global_backtrack = global_backtrack_lcs(s,t,indel_penalty,matrix)
global_output_lcs(global_backtrack, s, t, s_out, t_out, len(s),len(t), score)

2529
NQGIHKKLEAMCNPHYARCYFRMWGEIRVFNCMYQWYVLNYLCPTMAHAMFGYLTEPIMEVLRTIQVPYKPI----G--YICKAGKDEMAWWP-H--VIQNDIVMWGFKCNKDEPVPPTKTWVCMKELIKDCSWQGVE--FVGRTQGPEG--S-YQG-SPT-AGQDDGLQKQGRVMTLAWMCEQMDLRATDPRVRGAELEIQKDWEKPDICYMPCCHCWVEALHVGKLVCGYEQQM-E-SPINTEFTYNIAIMMVAWLNRLVDDYVPHMEYMKMEFRGRDPLCEYMGSGVCISYYILMYNS-IQY-QGYWW-C--LD-SADETAWSMTVL-K----HNDTTGMPNTMVDKDERRVQCQGIIAGGFWQCFDYSTKMTNLVVK-I--LVWRWWLHTDRSKEPDWVNMVWGFFMAGSVWAYARCCIYAEPVQAMDTMGLQTTPPWMHQDGRIRPGPY----R---WKEYVWADFKKYPRIPSWGKFHVNRMYRWNNMHHALCWST-K--GNPVD-------TA-AQSLYWQFNSDNYNVDTFFPCREMSPMRYIIMYWLTIWIENHCKDMNSFGTVDMPYHPPTPSGGWWCKTQMCHPD-KGVI-GCRNEHQQRQYGDEKCCCTTFMAFQNNCFHKQRGFW--K-GFEQATTDMNCTWAINYRGNIKVAQEPCLLEMTGMMGY---WRPCTAMNATPYAPHQNQCCQQHA----K---MKDQEPNFGKTFFWNLYILPTIHQWPLWWRQMRNYTPMNKEMKAQPVTRYAWVWEQKGVFIIWYVLAHKMGFNFPHATGGE---S--H--KMCEMINWRAIIPCGAYHNHKTRGCKAMKQDSFEAPGISPGVFDAEL------MMSFPPEVIGLPNN-WSRFVSSM-R------YKSEMAEMWQKC--M--WGWTNNSAHDV-------HQAPYPILGFYAGE------GKHSKFMCAMGHAPTW-VHVRMVLRSEPINLRNSWNEAGGMPNPLAIDEPP

Local Alignment Problem.<br>
Input: Two protein strings written in the single-letter amino acid alphabet.<br>
Sample input:<br>
MEANLY<br>
PENALTY<br>
Output: The maximum score of a local alignment of the strings, followed by a local alignment of these strings <br>
achieving the maximum score. <br>
Use the PAM250 scoring matrix for matches and mismatches as well as the indel penalty σ = 5.<br>
Sample output:<br>
15<br>
EANL-Y<br>
ENALTY

In [11]:
def local_backtrack_lcs(v, w, indel_penalty, matrix):
    s = numpy.zeros(shape = (len(v)+1,len(w)+1))
    local_backtrack = numpy.zeros(shape = (len(v)+1,len(w)+1))
    for i in range(len(v)+1):
        s[i,0] = -i*indel_penalty
    for i in range(len(w)+1):
        s[0,i] = -i*indel_penalty
    for i in range(1,len(v)+1):
        for j in range(1,len(w)+1):
            options = [s[i-1,j] - indel_penalty, s[i,j-1] - indel_penalty, s[i-1,j-1] + matrix[v[i-1]][w[j-1]], 0]
            s[i,j] = max(options)
            local_backtrack[i,j] = options.index(s[i,j]) + 1    #1 for up, 2 for left, 3 for diagonally, #4 for origin
            #4 means free ride from origin to somewhere
    #solve the bottom right cell of s and local_backtrack
    s[-1,-1] = 0
    k = len(v)
    l = len(w)
    options = [s[k-1,l] - indel_penalty, s[k,l-1] - indel_penalty, s[k-1,l-1] + matrix[v[k-1]][w[l-1]]]
    max_value, max_index = max((x, (i,j)) for i,row in enumerate(s) for j,x in enumerate(row))
    if max(options) < max_value:
        s[k,l] = max_value
        local_backtrack[k,l] = 5 #5 for free ride to sink from max_index
    else:
        s[k,l] = max(options)
        local_backtrack[k,l] = options.index(s[k,l]) + 1
    return local_backtrack, max_index

def local_output_lcs(local_backtrack, v, w, v_out, w_out, i, j, score, free_ride_to_end_position):
    if i == 0 or j == 0:
        print(score)
        print(v_out[::-1])
        print(w_out[::-1])
        return
    if local_backtrack[i,j] == 1:
        v_out = v_out + v[i-1]
        w_out = w_out + '-'
        score = score - indel_penalty
        local_output_lcs(local_backtrack, v, w, v_out, w_out, i-1, j, score, free_ride_to_end_position)
    elif local_backtrack[i,j] == 2:
        v_out = v_out + '-'
        w_out = w_out + w[j-1]
        score = score - indel_penalty
        local_output_lcs(local_backtrack, v, w, v_out, w_out, i, j-1, score, free_ride_to_end_position)
    elif local_backtrack[i,j] == 3:
        v_out = v_out + v[i-1]
        w_out = w_out + w[j-1]
        score += matrix[v[i-1]][w[j-1]]
        local_output_lcs(local_backtrack, v, w, v_out, w_out, i-1, j-1, score, free_ride_to_end_position)
    elif local_backtrack[i,j] == 4:
        local_output_lcs(local_backtrack, v, w, v_out, w_out, 0, 0, score, free_ride_to_end_position)
    elif local_backtrack[i,j] == 5:
        i = free_ride_to_end_position[0]
        j = free_ride_to_end_position[1]
        local_output_lcs(local_backtrack, v, w, v_out, w_out, i, j, score, free_ride_to_end_position)
        
import pandas
import numpy
numpy.set_printoptions(threshold=numpy.nan)

matrix = pandas.read_csv('PAM250.txt', sep = ' ', index_col = 'names')
indel_penalty = 5
s = 'ANAWECELNCHHKFFPHYVKVMEEGNLSDWICVRHWRWIFFITIMMKPVIMHQHRDGQMMQKFVQERQNCEIVSCKMLEVPMEHIISHTAFMSWAKYYSMQIGRDTIQAKYPRGYLQSTPYVTTEITDVMIDIEPLNNNGWMSHVPYYNCDWFPLKNWDAGEIMLAAEGCMQTQRSDWNMMSDMKIGWDWATWSCTQTCYYFIPHVESDGNSWCMKEFGKILPMMCCKVIVQGIWVMCLHHWHWVTACVRPWFHKIIRCMRNRLECVHHTKKMWPMFVRIVHGRRPSGGTYVNNGGVSYFYAVGRCLRFPDHMVIHRRRDHNVWQKFVHVRPMQQEEMRPGHWYTTVICMPWFEENYFVNHHALYIMAAEGPALGECYFEVMNKIYEMWHLNEGLWHEFCLVCVSLTCFGPEYTDAEFGDYWWMVYGHMPHCNAQHNPWYRCWAMPTKEWFVKLEGNMCGSYTSNYHSDKASMEQHLCWTCSPWQNVYLNMGEVLGNCFASVHSRVEYMPPICRPHDQNPYWIHMETTADNIWRPWTMGIFPYGARILFMPFFDSRGIPGQKSVTGQAGSLFVCMFYEKPEWDDMQTPCRFHTPFNSCYKFPNCGKVFMDWHEGKMATKGGFTEDDQLNARRRSREPAQNCSYANPSRNEMTYAPRVYTFGPNTPQWGPEGAGFFRHGLNIVDAYDQFSEHYPFMTKWANYPVIYNELCRNNLSIIYDWFPVNGGILEWLDQKVHKERCKYPEHYEHSYWVNNAAQEDFILNCMIWGAVYDTISMGGRDWPMTSDTIIEIIYRARVLGLSHFRATDTVAWPTYWFKMSNVRGDVGSYFTAFWKTVRCTDNDWEWMGREEFMLHQPPFSHHDVQAEKRDVLTLCGLENKRHTTTDHQKKGTKLREWFVYCR'
t = 'NFQGLLAYRQGTMEPNETGINESAVYHKMGTRFVHTDDKTICCMWAMNYDLECTYESKHHAEYETVLQCYAARMIIDHMVSAMAHSWNWPEEAWWMFIWYAYFDKDHGCIIQFHYMQHGEHMYPGTAALMVTCWQACDTMYIRMAEPNHEWESFDMVSLRQNCSTTHRTRSQRMPLTEPPADRMMHPHFKGCHLFKGVSTKPSEFKKQEHDQKYTSSLRRTVCDKKKIVHNCWMKEACPYMNIYIRAIGLKMWMNSDDAPGRHVYMPVGNCDNPAMAQHERLWISYWFIFTSWKNQSEGLLELWCPMFVTIVHGRRPSGGTYVFNGGVSYFYYPFWIVGRCLRFPDAMVIHRRRDHNVWQKKMLLHYVQMCAQMRPCHTSFQPIKMPWFEENYFVNHMAAEGPMNKIYEMGSYYAPSHLNAGLWLEFCTYFGDAKFGCYWWNPEMVYGHRYRPMYDESPHCHYLKDMYAQHNKRPTHRWYIAPYDWYLVKLEVYMCGSYTSNYHSDKASMEQHGCWPCSQWQNVYLNMAHCQIDWVVHSPVEYMAPICRGMDGHDPMSFRMAGNIWRPWTMGIYGARILFMVPAYDFFDSRGTWRYSPGQKSVTPCAGSLFVCWFYEKPECGLRFADDMCETWYSANMWIKFPNHQRCGKVFMDWHTIMFQLKMATATIYHVKKASMRFVLIGHVPRTWSGAWHMNEAKFFPPKVILSDPNFPDFPWFQGHICKLTLNMSPQAPKPKNDWMFKYYNYMQYPPLPQPNWKWKQDWRMMFTYMISNWHQARAELYVENAWDSQLLAHQIEGKSPMGMQARQTLCDWMTENRIWDKLPGIDNGQMAMGAMAIFTNALRRSYHIKLITQWHCYQNEIAIRWSDMGPRSDAMGQRYRMAPRNDDLKLMDLVIAYWSCWLEQYLYHLRFANKMYNGTICAISVMVQPRRQDNARDQAPDNYKCRPDTRKTDEICTMQWANYFKLNSRQRNTRGHAHYAKSEDRNPKHFKYEMN'
s_out = ''
t_out = ''
score = 0
local_backtrack_function_output = local_backtrack_lcs(s,t,indel_penalty,matrix)
local_backtrack = local_backtrack_function_output[0]
free_ride_to_end_position = local_backtrack_function_output[1]
local_output_lcs(local_backtrack, s, t, s_out, t_out, len(s),len(t), score, free_ride_to_end_position)

1225
NAWECELNCHH-K-FFPHYVKVMEEGNLSDWICVRHWRWIFF-ITIMMK-P--VI-MH-QHRDGQMMQKFVQERQNCEIVSCKMLEVPMEHIISHTAFMSWAKYYSMQIGRDTIQAKYPRGYLQSTPYVTTEITDVMIDIEPLNNNGWMSHVPYYN-CDWF-PLKNWDAGEIMLAAEGCMQTQRSDWNMMSDMK-IGWDWATWSCTQTCYYFIPHVESDG-NSWCMK-E-F-GK-I-LPMMCCKVIVQGIWVMCLHHWHWVTACVRPWFHKIIRCMRNRLECVHHTKKMW-PMFVRIVHGRRPSGGTYVNNGGVSYFY-A--V-GRCLRFPDHMVIHRRRDHNVWQKFVHVRPMQQ-EEMRPGH-WYTTVICMPWFEENYFVNHHALYIMAAEGPALGECYFEVMNKIYEMWHLNEGLWHEFC--LVCVSLTCF--GPEYTDAEFGD-YWWMVYGHMPHCN------AQHNPW--YRCWAMPTKEWF-VKLEGNMCGSYTSNYHSDKASMEQHLCWTCSPWQNVYLNMGEVLGNCFASVHSRVEYMPPICRPHD-QNPYWIHMETTADNIWRPWTMGIFPYGARILFM-P---FFDSRGI----PGQKSVTGQAGSLFVCMFYEKPEWD-DM-QTPC--RFHTPFNSCYKFPN---CGKVFMDWHEGKMATKGGFTEDDQLN-ARRRSREPAQ-NCSYANPSR-NEMTY-APRVYTFGPNTPQ--WGPEGAGFFRHGLNIVDAYDQFSEHYPFMTKWANYPVIYNELCRNNLSIIYDWFPVNGGIL-EWLDQK----VHKER-CKY-PEHYEHSYWVN-NAAQE--DFILNCMIWGAVYDTISMGGRDW-PMTS-DTIIEIIYRARVLGLSH-FRATDTVAWPTYWFKMSNVRGD-VG-SY-FTAFWKT-VRCTD-N-D-WE-WMGREEFMLHQPPFSHHDVQAEKRDVLTLCGLENKRHTTTDHQ
AEYETVLQCYAARMIIDHMVSAMAHS-W

Edit Distance Problem: Find the edit distance between two strings ('edit distance', Vladimir Levenshtein, 1966).<br>
Input: Two strings.<br>
Sample input:<br>
PLEASANTLY<br>
MEANLY<br>
Output: The edit distance between these strings.<br>
Sample output: <br>
5

In [12]:
def global_backtrack_lcs(v, w, indel_penalty, matrix):
    s = numpy.zeros(shape = (len(v)+1,len(w)+1))
    global_backtrack = numpy.zeros(shape = (len(v)+1,len(w)+1))
    for i in range(len(v)+1):
        s[i,0] = -i*indel_penalty
    for i in range(len(w)+1):
        s[0,i] = -i*indel_penalty
    for i in range(1,len(v)+1):
        for j in range(1,len(w)+1):
            if v[i-1] == w[j-1]:
                mutation_penalty = 0
            else:
                mutation_penalty = 1
            options = [s[i-1,j] - indel_penalty, s[i,j-1] - indel_penalty, s[i-1,j-1] - mutation_penalty]
            s[i,j] = max(options)
            global_backtrack[i,j] = options.index(s[i,j]) + 1    #1 for up, 2 for left, 3 for diagonally
    return global_backtrack

def global_output_lcs(global_backtrack, v, w, v_out, w_out, i, j, score):
    if i == 0 or j == 0:
        if i == 0 and j != 0:
            v_out = v_out + w[0]
            w_out = w_out + '-'
            score = score - indel_penalty
            print(score)
        if i != 0 and j == 0:
            v_out = v_out + '-'
            w_out = w_out + v[0]
            score = score - indel_penalty
            print(score)
        if i == 0 and j == 0:
            print(score)
        print(w_out[::-1])
        print(v_out[::-1])
        return
    if global_backtrack[i,j] == 1:
        v_out = v_out + '-'
        w_out = w_out + v[i-1]
        score = score - indel_penalty
        global_output_lcs(global_backtrack, v, w, v_out, w_out, i-1, j, score)
    elif global_backtrack[i,j] == 2:
        v_out = v_out + w[j-1]
        w_out = w_out + '-'
        score = score - indel_penalty
        global_output_lcs(global_backtrack, v, w, v_out, w_out, i, j-1, score)
    else:
        if v[i-1] == w[j-1]:
            mutation_penalty = 0
        else:
            mutation_penalty = 1
        v_out = v_out + w[j-1]
        w_out = w_out + v[i-1]
        score -= mutation_penalty
        global_output_lcs(global_backtrack, v, w, v_out, w_out, i-1, j-1, score)
        
indel_penalty = 1
s = 'LPIKYDDAATDLGRQAHLAHQAISMTDKDTWACALISGGGIENYMMRYTFKKMYHRDPQVIYPISTNKELGCNIDYMKFGPTHQFYITNLRIFSKHRPWSEKTYDIRVEVNRFSPMHCHTHQANREHDPRFFPHHQQNKVCHMCTKEQYPVLMNDYWSPPWPYPAYIYSWLVKLVCTNNTIHYFVDASQHHPYCEEMYAWIDVKTYCFCWFTQTKHQIEQQWIGESVGCWTQELQTMITNYKKIMLVDDCVLFYGDQCYNHPMWHGTKNITYVSAWVTVMKEECVTHPPKHLSPYFMQAMTVDHMKQKQKSEATPIDYECKVFKEHTPIQHCTWPLKTSWGMLSKDSPTHQDLKYHMCTMQRLQKIPCAIPRWCQEFVQTQPLFSIEGCYCNENCLAPNAPETRARAEFWMTIVVLYTYWISTFGLKASKNWAKPQSSCMHQVWHYDWAFDVCKMYMERPFYICGDQITVFVLCTPNSCIKLAVAEYLRAQYLYMDMNAMVCVTLFVFGWYFYFVNSVLPFLRYMIWPEDSYKCCTDTSNHAGHPEMGCRLKHSLVCGAMEWVFIIMHNCWHSCRKHTRLFYLNKMYIRPAVISIKTLLAISNILRAPQMCYYFHRYVKEFPMSGMDTDTSPDTYYFTLMTRGSNCHWTTCRNDPPSQRFLLNYTERDGSLRFWYCQDTTICTSHHERMWWNMFTIKFCIKLGKSCRQRFDKIEQGFEAKQVNPNSHMFFASRNDNTYSHYHNQKCRCRVTDNHHQTEMKCCCPLMSPPGHEFGEMWNDEGTLCQYFICYFVENGVMNIKERDERDMCPYEMFPFQIDWRLSDVHENIHRTQVFIKRYQVYRPKCPAMEDPIAQYDYYGILSQSDQIQY'
t = 'LPIKYDDAAKDPYGRTAHLAHQAISMTDKDHNRWACAYISGGGFEWQIFQWYMMQYPTKKMSDPQVIYVISTNLGPNIDYMKFGPTHQFYSFNFSIHYDIIDSYLRFSPMHCHTHMILANREHDPAFFPHHQQNKVCHKCTKEQYPVLMNDYWSDFKDIIPWPYPAYIYSWLVKLYCNHYCYVDAMQHHPYCEEMYAWIDHWMTRHTQTKHQIEQQWQTMIMNYCKIMTEQMMVDDCVYWSWAHAYGDQCYNHPMWHGQKNITYMKEECVNGSGLQNPPKIEAGPLLASLSIHKKTQAMTVDHMKQKQKSPKAYCCKVFKEEYFTYCIGMFSKDSPTIYYLKQDLKYEAFGIWHMCTAIPRWCQFKWFGPYMFVWTQPLFPDEDWWEGCYCNENCQQWQAPNAPETRAWRNHKPEKVVTQEFWGTIVVLYTYWIEHWTFGLKASKYRFDHRTVWAKSAGAPQSCMHQVWHYDWAFSVCKMYMYRPVMHSMVVKAVFVLCTPNSCIKDQYIYCTLDYCHYLYMDMTAHDCVTLNVFVIGSVLPFARMMIMIWESNMQMRETEDSYKCFTDTSNHAQESHPTMPCRYQHSLHCDAMEMHWHSCRFHLNKMYIRPHVISIVTLLAISNNKILRLPQMCYYFNRMFVPPQRLEFPMSGMDTDTSPKLTEHGVAQGLMTRDSNTMSCHQTTCRNDPPSQIFLLTERDTNKWYKLSISLGFWYCQDTRQWYICTSHHERRWWNMFTIKFCIKLGMTWNVEYSCQRFDKICFIIVNPNSHMFFASRNVNTYSHYHNQMCRCNHHQTEHKCCCWLMSPPGHEFQKMWNDEGTLGGLQYFICYFVEKQGKWFMENMNIKERDPFLSYNSFDADVHEVFMIHNNQVFIKRYQVYRPKFPAMEDPRAQLSQSDQIFW'
s_out = ''
t_out = ''
score = 0
global_backtrack = global_backtrack_lcs(s,t,indel_penalty,matrix)
global_output_lcs(global_backtrack, s, t, s_out, t_out, len(s),len(t), score)

-392
LPIKYDDAATDL-GRQAHLAHQAISMTDKDT--WACALISGGGIEN-----YMMRY-TFKKMYHRDPQVIYPISTNKELGCNIDYMKFGPTHQFYITNLRIFSKHRPWSEKTYDIRVEVNRFSPMHCHTHQ--ANREHDPRFFPHHQQNKVCHMCTKEQYPVLMNDYWSP-----PWPYPAYIYSWLVKLVCTNNTIHYFVDASQHHPYCEEMYAWIDVK-TYCFCWFTQTKHQIEQQWIGESVGCWTQELQTMITNYKKIML----VDDCVLF-----YGDQCYNHPMWHGTKNITY-----V--SAWVTVMKEECVTHPPKHLSPYFM-QAMTVDHMKQKQKSEATPIDYECKVFKEHTPIQHCTWPLKTSWGMLSKDSPTHQDLKYHMCTMQRLQKIPC-AIPRWCQE--F-----VQTQPLFSIE----GCYCNENCL---APNAPETRA-RA---E------FWMTIVVLYTYWIS--TFGLKASKN-------WAK----PQSSCMHQVWHYDWAFDVCKMYMERPFYICGDQITVFVLCTPNSCIKLAVAEY--LRAQ-YLYMDMNAMVCVTLFVFGWYFYFVNSVLPFLRYMI--WP------E--DSYKCCTDTSNHAG--HPEMGCRLKHSLVCGAMEWVFIIMHNCWHSCRKHTRLFYLNKMYIRPAVISIKTLLAISN--ILRAPQMCYYFHRY-VK----EFPMSGMDTDTSPD-TYYFT---LMTRGSN---CHWTTCRNDPPSQRFLLNYTERDG------S--LRFWYCQDTT---ICTSHHERMWWNMFTIKFCIKLGK------SCRQRFDKIEQGFEAKQVNPNSHMFFASRNDNTYSHYHNQKCRCRVTDNHHQTEMKCCCPLMSPPGHEFGEMWNDEGTLC--QYFICYFVEN-GV--M-N--IKERDERDMCPYEMFPFQIDWRLSDVHEN--IHRTQVFIKRYQVYRPKCPAMEDPIAQYDYYGILSQSDQI

Fitting Alignment Problem: Construct a highest-scoring fitting alignment between two strings.<br>
Input: Strings v and w as well as a matrix Score (where v has length at most 1000 and w has length at most 100).<br>
Use the simple scoring method in which matches count +1 and both the mismatch and indel penalties are 1.<br>
Sample input:<br>
GTAGGCTTAAGGTTA<br>
TAGATA<br>
Output: A highest-scoring fitting alignment of v and w as defined by the scoring matrix Score.<br>
2<br>
TAGGCTTA<br>
TAGA--TA

In [13]:
def local_backtrack_lcs(v, w, indel_penalty):
    s = numpy.zeros(shape = (len(v)+1,len(w)+1))
    local_backtrack = numpy.zeros(shape = (len(v)+1,len(w)+1))
    for j in range(len(w)+1):
        s[0,j] = -j*indel_penalty
    for i in range(1,len(v)+1):
        for j in range(1,len(w)+1):
            if v[i-1] == w[j-1]:
                mutation_penalty = 1
            else:
                mutation_penalty = -1
            options = [s[i-1,j] - indel_penalty, s[i,j-1] - indel_penalty, s[i-1,j-1] + mutation_penalty]
            s[i,j] = max(options)
            local_backtrack[i,j] = options.index(s[i,j]) + 1    #1 for up, 2 for left, 3 for diagonally, #4 for origin
            #4 means free ride from origin to somewhere
    #solve the bottom right cell of s and local_backtrack
    s[-1,-1] = 0
    k = len(v)
    l = len(w)
    if v[k-1] == w[l-1]:
        mutation_penalty = 1
    else:
        mutation_penalty = -1
    options = [s[k-1,l] - indel_penalty, s[k,l-1] - indel_penalty, s[k-1,l-1] + mutation_penalty]
    extra_options = list(s[:,-1][:-1])
    if max(extra_options) >= max(options):
        #free ride back to max_index
        max_value = max(extra_options)
        max_index = (extra_options.index(max_value),len(w))
        s[k,l] = max_value
        local_backtrack[k,l] = 5 #5 for free ride to sink from max_index
    else:
        #back one step
        max_value = max(options) 
        max_index = ('na','na')
        s[k,l] = max_value
        local_backtrack[k,l] = max_value + 1 #1 for up, 2 for left, 3 for diagonally
    #print(s)
    #print(local_backtrack)
    #print(max_index)
    return local_backtrack, max_index

def local_output_lcs(local_backtrack, v, w, v_out, w_out, i, j, score, free_ride_to_end_position):
    if i == 0 or j == 0:
        print(score)
        print(v_out[::-1])
        print(w_out[::-1])
        return
    if local_backtrack[i,j] == 1:
        v_out = v_out + v[i-1]
        w_out = w_out + '-'
        score = score - indel_penalty
        local_output_lcs(local_backtrack, v, w, v_out, w_out, i-1, j, score, free_ride_to_end_position)
    elif local_backtrack[i,j] == 2:
        v_out = v_out + '-'
        w_out = w_out + w[j-1]
        score = score - indel_penalty
        local_output_lcs(local_backtrack, v, w, v_out, w_out, i, j-1, score, free_ride_to_end_position)
    elif local_backtrack[i,j] == 3:
        v_out = v_out + v[i-1]
        w_out = w_out + w[j-1]
        if v[i-1] == w[j-1]:
            mutation_penalty = 1
        else:
            mutation_penalty = -1
        score += mutation_penalty
        local_output_lcs(local_backtrack, v, w, v_out, w_out, i-1, j-1, score, free_ride_to_end_position)
    elif local_backtrack[i,j] == 4:
        local_output_lcs(local_backtrack, v, w, v_out, w_out, 0, 0, score, free_ride_to_end_position)
    elif local_backtrack[i,j] == 5:
        i = free_ride_to_end_position[0]
        j = free_ride_to_end_position[1]
        local_output_lcs(local_backtrack, v, w, v_out, w_out, i, j, score, free_ride_to_end_position)
        

indel_penalty = 1
s = 'ACGACCACAGATACCGCTATTCACTATATCGTT'
t = 'GATACACT '
s_out = ''
t_out = ''
score = 0
local_backtrack_function_output = local_backtrack_lcs(s,t,indel_penalty)
local_backtrack = local_backtrack_function_output[0]
free_ride_to_end_position = local_backtrack_function_output[1]
local_output_lcs(local_backtrack, s, t, s_out, t_out, len(s),len(t), score, free_ride_to_end_position)

4
GATACCGCT-
GATACA-CT 


Overlap Alignment Problem.<br>
Input: Two strings v and w, each of length at most 1000.<br>
Sample input:<br>
PAWHEAE<br>
HEAGAWGHEE<br>
Output: The score of an optimal overlap alignment of v and w, <br>
followed by an alignment of a suffix v' of v and a prefix w' of w achieving this maximum score. <br>
Use an alignment score in which matches count +1 and both the mismatch and indel penalties are 2.<br>
Sample output:<br>
1<br>
HEAE<br>
HEAG

In [14]:
def overlap_backtrack_lcs(v, w, indel_penalty):
    s = numpy.zeros(shape = (len(v)+1,len(w)+1))
    overlap_backtrack = numpy.zeros(shape = (len(v)+1,len(w)+1))
    for j in range(len(w)+1):
        s[0,j] = -j*indel_penalty
    for i in range(1,len(v)+1):
        for j in range(1,len(w)+1):
            if v[i-1] == w[j-1]:
                mutation_penalty = 1
            else:
                mutation_penalty = -2
            options = [s[i-1,j] - indel_penalty, s[i,j-1] - indel_penalty, s[i-1,j-1] + mutation_penalty]
            s[i,j] = max(options)
            overlap_backtrack[i,j] = options.index(s[i,j]) + 1    #1 for up, 2 for left, 3 for diagonally, #4 for origin
            #4 means free ride from origin to somewhere
    #solve the bottom right cell of s and local_backtrack
    s[-1,-1] = 0
    k = len(v)
    l = len(w)
    if v[k-1] == w[l-1]:
        mutation_penalty = 1
    else:
        mutation_penalty = -2
    options = [s[k-1,l] - indel_penalty, s[k,l-1] - indel_penalty, s[k-1,l-1] + mutation_penalty]
    extra_options = list(s[-1,:][:-1])
    if max(extra_options) >= max(options):
        #free ride back to max_index
        max_value = max(extra_options)
        max_index = (len(v),extra_options.index(max_value))
        s[k,l] = max_value
        overlap_backtrack[k,l] = 5 #5 for free ride to sink from max_index
    else:
        #back one step
        max_value = max(options) 
        max_index = ('na','na')
        s[k,l] = max_value
        overlap_backtrack[k,l] = max_value + 1 #1 for up, 2 for left, 3 for diagonally
    #print('s',s)
    #print('b',overlap_backtrack)
    #print(max_index)
    return overlap_backtrack, max_index

def overlap_output_lcs(overlap_backtrack, v, w, v_out, w_out, i, j, score, free_ride_to_end_position):
    if i == 0 or j == 0:
        print(score)
        print(v_out[::-1])
        print(w_out[::-1])
        return
    if overlap_backtrack[i,j] == 1:
        v_out = v_out + v[i-1]
        w_out = w_out + '-'
        score = score - indel_penalty
        overlap_output_lcs(overlap_backtrack, v, w, v_out, w_out, i-1, j, score, free_ride_to_end_position)
    elif overlap_backtrack[i,j] == 2:
        v_out = v_out + '-'
        w_out = w_out + w[j-1]
        score = score - indel_penalty
        overlap_output_lcs(overlap_backtrack, v, w, v_out, w_out, i, j-1, score, free_ride_to_end_position)
    elif overlap_backtrack[i,j] == 3:
        v_out = v_out + v[i-1]
        w_out = w_out + w[j-1]
        if v[i-1] == w[j-1]:
            mutation_penalty = 1
        else:
            mutation_penalty = -2
        score += mutation_penalty
        overlap_output_lcs(overlap_backtrack, v, w, v_out, w_out, i-1, j-1, score, free_ride_to_end_position)
    elif overlap_backtrack[i,j] == 4:
        overlap_output_lcs(overlap_backtrack, v, w, v_out, w_out, 0, 0, score, free_ride_to_end_position)
    elif overlap_backtrack[i,j] == 5:
        i = free_ride_to_end_position[0]
        j = free_ride_to_end_position[1]
        overlap_output_lcs(overlap_backtrack, v, w, v_out, w_out, i, j, score, free_ride_to_end_position)
        

indel_penalty = 2
s = 'GTAACGGAGGTATACGTTGGCGGTCCGAATATGTCATAGAGCTGAGCTCCAGTTACTTGCCTGCCTCAAAATTAAAGTCTTGCGGTTTTGGGGCGAGACCTGTATCGGTCTTTTGCTTGCACTCGGGGCGCCCGCGCTAGGGACAGGGGATGAATATCTGGATGTCTAATGTATGGGGGATGCGTTGAGGAGCAATCCTCTCACAGGATTCCCTCGTGTGCACGGGAAAAGTTGCGGCTAACAGATAGGACCCTTAATGGATTTCCAACTCTGAAGCACATCTTAACTGTACTGTAGCCTGACACTCTCTATGTTCGGCCCAGCCTGCACTGTAACTGTGCGTAATGCAAGCATGCTTCGGTCTGCCACTGTTGCTTTATAGTCGAACGCCCACTGTTAGTCCTCGAGAACTTCTTCGCGCCTGTTCTAAACCTACGGACATTACAATTAAATTCGCACTGCGAGAAGCGTTGAGGTAATCATCACTGACAGTTCGTCGATCCGCAAAGTACAAAAGCCGACAAATCGGGCTCCCTCATATGTGCTTTGACCCCGTCAGAGAATTATCGCGAGACGCCGGCAATGTTTGCAACCACGAAAACCCGCGGCTATCCGACTTGAACCGTGTGCCGCTACCACCAGGTATACACACACCCTTGTGAGAGTCAAATTGTGCGAAGACGGGACTATATTTTGAAAGCGTCACCGGGAAGACGTAGGCATACGAGCCTAATCATAGTTAAAGCAAGGTATTTCTACTATTCAGCATCCATAAATATGGAGCGACAAGCAGCCTTTTCTACGACGGGTTCGACAAACGTGATCCCTTGGCAAAT'
t = 'CCCGCCTGGCTGGCTTGCATCGGTACACGCACACCTTTGAGGGTCAGGTTATACGAAAAAGAACTTACTGTTTTAGAAACGTTACGTGGGAAGGGTGGTATCGATATCTAGCCAAGAATTAACGGATAGGTATTTTCCATGAGGTCGGCATTATAATATGGAACGACAAGCAGCCTTCTCAACACGGATTCGCAAATCATCTCTCTTGTAAAATAAGATGCTCTCCGGAAGAATCGGTTTACTATAAGCTGACGTTCTTCCCGGCCACAGGAATGCCGCGATTAGTAACACTACAATATAAATATAAAATAGACCATACCCAGCAACGTTCGCTTCAGAGGTAAAACTTCCTGACGAGCAGGCGATAAGTTCAAGGTATCAGGGACCGTTATGATGAACCATTCGCTTTGAAAAGAGTTGCTACTTAGATCAATAGATCTGTCGGAATTTATGGAGAGCGCCCCTTGGTCAAGAAATTGACCAATAAATACATAACTGGATGATTCAGACGAGCTGACTGGGTCAGTTCAGCTAATTCGCATATTGGCGGAAACTACACAAGCCCAATGCCCTGTCAGTACGAATTAAGAAAGACATCCAGCAGGCTAACGTCACCTGCGGGTTACGATTTCGCTCACGAGAGGTGGTAGCGGTGCTGGTTGCTCAAGGACCACGCTCTTGGGATCCCGGGCTTAATCTGACGACCTACCAAATGGCAACAAACCTGAAATACCTTTTTTGAGCTGATAATGCTTTCCGCACTTGAAGGATTAAATCCAGTAACACCAGCGCCTAATAGGCGTTAAGACTCGGCCGTTTTATTGATCGCCAATTTTATTTCGCTACTCAGTGCTATTAGCTAGGAAGTGGGCTTTGTATATCGTTGCCTTTCATAATCATCATGACGGCGGGCATCGCTCTGCAAC'
s_out = ''
t_out = ''
score = 0
overlap_backtrack_function_output = overlap_backtrack_lcs(s,t,indel_penalty)
overlap_backtrack = overlap_backtrack_function_output[0]
free_ride_to_end_position = overlap_backtrack_function_output[1]
overlap_output_lcs(overlap_backtrack, s, t, s_out, t_out, len(s),len(t), score, free_ride_to_end_position)

21
CC-G--TGTGCCG-CTACCACCAGGTATACACACACCCTTGTGAGAGTCAAATTGTGCGAAGACGGGACT-A-TATTTT-GAAAGCGTCACC-GGGAAGACGTAGGCATACGAGC-CTAATCATAG--TTAAAGCA-AGGTATTT-CTACT-AT-TCAGCATCCATAAATATGGAGCGACAAGCAGCCTTTTCTACGACGGGTTCGACAAACGTGATC-C-CTTGGCAAAT
CCCGCCTG-GCTGGCTTGCATC-GGTACACGCACACC-TT-TGAGGGTCAGGTTATACGAAAAAGA-ACTTACTGTTTTAGAAA-CGTTACGTGGGAAGG-GT-GGTAT-CGATATCTAGCCA-AGAATTAACGGATAGGTATTTTCCA-TGAGGTCGGCATT-ATAA-TATGGAACGACAAGCAGCCTTCTCAAC-ACGGATTCG-CAAA--TCATCTCTCTTGTAAAAT


Alignment with Affine Gap Penalties Problem.<br>
Input: Two amino acid strings v and w (each of length at most 100).<br>
Sample input:<br>
PRTEINS<br>
PRTWPSEIN<br>
Output: The maximum alignment score between v and w, followed by an alignment of v and w achieving this maximum score. <br>
Use the BLOSUM62 scoring matrix, a gap opening penalty of 11, and a gap extension penalty of 1.<br>
Sample output:<br>
8<br>
PRT---EINS<br>
PRTWPSEIN-

In [15]:
def gap_backtrack_lcs(v, w, indel_penalty, matrix):
    #introducing three layers to account for gap extension
    lower = numpy.zeros(shape = (len(v)+1,len(w)+1))
    middle = numpy.zeros(shape = (len(v)+1,len(w)+1))
    upper = numpy.zeros(shape = (len(v)+1,len(w)+1))
    gap_backtrack = numpy.zeros(shape = (len(v)+1,len(w)+1))
    for i in range(1,len(v)+1):
        lower[i,0] = max(lower[i-1,0] - gap_extension_penalty, middle[i-1,0] - gap_opening_penalty)
        middle[i,0] = lower[i,0]
    for j in range(1,len(w)+1): 
        upper[0,j] = max(upper[0,j-1] - gap_extension_penalty, middle[0,j-1] - gap_opening_penalty)
        middle[0,j] = upper[0,j]
    for i in range(1,len(v)+1):
        for j in range(1,len(w)+1):
            options_lower = [lower[i-1,j] - gap_extension_penalty, middle[i-1,j] - gap_opening_penalty]
            lower[i,j] = max(options_lower)
            options_upper = [upper[i,j-1] - gap_extension_penalty, middle[i,j-1] - gap_opening_penalty]
            upper[i,j] = max(options_upper)
            options_middle = [lower[i,j], upper[i,j], middle[i-1,j-1] + matrix[v[i-1]][w[j-1]]]
            middle[i,j] = max(options_middle)

            gap_backtrack[i,j] = options_middle.index(middle[i,j]) + 1    #1 for up, 2 for left, 3 for diagonally
    print('lower',lower)
    print('upper',upper)
    print('middle',middle)
    print('back',gap_backtrack)
    return gap_backtrack

def gap_output_lcs(gap_backtrack, v, w, v_out, w_out, i, j, score):
    if i == 0 or j == 0:
        if i == 0 and j != 0:
            v_out = v_out + '-'
            w_out = w_out + w[0]
            score = score - gap_opening_penalty #OR OPENING!!!!???????
            print(score)
        if i != 0 and j == 0:
            v_out = v_out + v[0]
            w_out = w_out + '-'
            score = score - gap_opening_penalty
            print(score)
        if i == 0 and j == 0:
            print(score)
        print(v_out[::-1])
        print(w_out[::-1])
        return
    if gap_backtrack[i,j] == 1:
        v_out = v_out + v[i-1]
        w_out = w_out + '-'
        score = score - gap_opening_penalty
        gap_output_lcs(gap_backtrack, v, w, v_out, w_out, i-1, j, score)
    elif gap_backtrack[i,j] == 2:
        v_out = v_out + '-'
        w_out = w_out + w[j-1]
        score = score - gap_opening_penalty
        gap_output_lcs(gap_backtrack, v, w, v_out, w_out, i, j-1, score)
    elif gap_backtrack[i,j] == 3:
        v_out = v_out + v[i-1]
        w_out = w_out + w[j-1]
        score += matrix[v[i-1]][w[j-1]]
        gap_output_lcs(gap_backtrack, v, w, v_out, w_out, i-1, j-1, score)
        
import pandas
matrix = pandas.read_csv('blosum62.txt', sep = ' ', index_col = 'names')
gap_opening_penalty = 11
gap_extension_penalty = 1
s = 'PRTEINS'
t = 'PRTWPSEIN'
s_out = ''
t_out = ''
score = 0
gap_backtrack = gap_backtrack_lcs(s,t,indel_penalty,matrix)
gap_output_lcs(gap_backtrack, s, t, s_out, t_out, len(s),len(t), score)

lower [[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-2. -2. -2. -2. -2. -2. -2. -2. -2. -2.]
 [-3. -3.  1. -3. -3. -3. -3. -3. -3. -3.]
 [-4. -4.  0.  6. -4. -4. -4. -4. -4. -4.]
 [-5. -5. -1.  5.  3. -5. -5. -2. -5. -5.]
 [-6. -6. -2.  4.  2.  0. -6. -3.  2. -6.]
 [-7. -7. -3.  3.  1. -1.  1. -4.  1.  8.]]
upper [[ 0. -1. -2. -3. -4. -5. -6. -7. -8. -9.]
 [ 0. -1. -2. -3. -4. -5. -6. -7. -8. -9.]
 [ 0. -1. -2.  1.  0. -1. -2. -3. -4. -5.]
 [ 0. -1. -2. -3.  6.  5.  4.  3.  2.  1.]
 [ 0. -1. -2. -3. -4.  3.  2.  1.  0. -1.]
 [ 0. -1. -2. -3. -4. -5.  0. -1. -2.  2.]
 [ 0. -1. -2. -3. -4. -5. -6.  1.  0. -1.]
 [ 0. -1. -2. -3. -4. -5. -6. -6.  1.  0.]]
middle [[ 0. -1. -2. -3. -4. -5. -6. -7. -8. -9.]
 [-1.  7. -1. -1. -1.  3. -1. -1. -1. -1.]
 [-2. -1. 12.  1.  0. -1.  2. -1. -2. -1.]
 [-3. -1.  1. 17.  6.  5.  4.  3.  2.  1.]
 [-4. -1.  0.  6. 14.  5.  5.  9.  0.  2.]
 [-5. -1. -1.  5.  3. 11.  3.  2. 13.  2.]
 [-6. -1. -1.  4.  2.  1. 12.  3.